name: "Terraform Infrastructure Change Management Pipeline with GitHub Actions"

on:
  push:
    branches:
      - main
      
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name:  Checkout the repository to the runner
        uses: actions/checkout@v4
      # Set up Terraform
      - name: Setup Terraform  with specified version on the runner
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.7

      # Configure AWS credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Initialize terraform scripts
        run: terraform init

      # - name: formatting terraform script
      #   run: terraform fmt

      # - name: validating terraform script
      #   run: terraform validate

      - name: applying terraform script
        run: terraform destroy --auto-approve

